build: verify tutorial cache directory exists
uw-ssec/tutorials pull request #93
Opened 2024-06-12 16:20 UTC by anantmittal

2024-06-12 17:06 UTC, lsetiawan commented on resources/src/ssec_tutorials/setup.py
> +        TUTORIAL_CACHE.mkdir(parents=True, exist_ok=True)
This is not needed has the code above will make the directory and it's parents by default.

2024-06-12 17:07 UTC, lsetiawan requested changes
The verify doesn't really need to happen. I think it would be better to do an assert after the `TUTORIAL_CACHE.mkdir` call in the existing code lines above. What you have has too many duplications.

2024-06-12 20:40 UTC, lsetiawan commented
@anantmittal can you confirm that this works now?

2024-06-13 18:09 UTC, lsetiawan approved these changes

2024-06-13 18:17 UTC, anantmittal commented
> @anantmittal can you confirm that this works now?

Yes, this works.

2024-06-13 18:17 UTC, merged